name: SonarCloud Scan 1
on:
  push:
    branches:
      - develop-x
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
#    env: 
#      RESEND_API_KEY: $RESEND_API_KEY
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Install dependencies
#        run: yarn
#      - name: Test and coverage
#        run: yarn jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
