name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
on:
  push:
#    branches-ignore:
    branches:
      -  develop
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
          # Supprimer le dossier .next (cache de build précédent)
      - name: Remove .next cache
        run: rm -rf .next
      - name: Build Project Artifacts
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
